import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import AuthModal from "@/components/AuthModal";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { Database } from "@/types_db";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body
        className={`${inter.className} overflow-x-hidden bg-neutral-900 text-neutral-400`}
      >
        <header>
          <NavBar session={session} />
        </header>
        <main>{children}</main>
        <AuthModal />
      </body>
    </html>
  );
}
